/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Crypto-Conditions"
 * 	found in "CryptoConditions.asn"
 */

#include "ConditionTypes.h"

int
ConditionTypes_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	//td->encoding_constraints.general_constraints = asn_DEF_BIT_STRING.encoding_constraints.general_constraints;
	// *******   CHECK  ************ above is remmed out because of change of typedef int(asn_constr_check_f)(
	//struct asn_TYPE_descriptor_s *type_descriptor,   it wasnt a const trcut before
	// I think the below static void sets the eoncoding constraint now however
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using BIT_STRING,
 * so here we adjust the DEF accordingly.
 */
static void
ConditionTypes_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->op   = asn_DEF_BIT_STRING.op;
/*	td->op->print_struct   = asn_DEF_BIT_STRING.op->print_struct;*/
	td->encoding_constraints = asn_DEF_BIT_STRING.encoding_constraints;
/*	td->op->ber_decoder    = asn_DEF_BIT_STRING.op->ber_decoder;
	td->op->der_encoder    = asn_DEF_BIT_STRING.op->der_encoder;
	td->op->xer_decoder    = asn_DEF_BIT_STRING.op->xer_decoder;
	td->op->xer_encoder    = asn_DEF_BIT_STRING.op->xer_encoder;
	td->op->uper_decoder   = asn_DEF_BIT_STRING.op->uper_decoder;
	td->op->uper_encoder   = asn_DEF_BIT_STRING.op->uper_encoder;*/
	if(!td->encoding_constraints.per_constraints)
		td->encoding_constraints.per_constraints = asn_DEF_BIT_STRING.encoding_constraints.per_constraints;
	td->elements       = asn_DEF_BIT_STRING.elements;
	td->elements_count = asn_DEF_BIT_STRING.elements_count;
	td->specifics      = asn_DEF_BIT_STRING.specifics;
}

void
ConditionTypes_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, enum asn_struct_free_method contents_only) {
	ConditionTypes_1_inherit_TYPE_descriptor(td);
	td->op->free_struct(td, struct_ptr, contents_only);
}

int
ConditionTypes_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ConditionTypes_1_inherit_TYPE_descriptor(td);
	return td->op->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
ConditionTypes_decode_ber(const asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ConditionTypes_1_inherit_TYPE_descriptor(td);
	return td->op->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
ConditionTypes_encode_der(asn_TYPE_descriptor_t *td,
		const void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ConditionTypes_1_inherit_TYPE_descriptor(td);
	return td->op->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
ConditionTypes_decode_xer(const asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ConditionTypes_1_inherit_TYPE_descriptor(td);
	return td->op->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
ConditionTypes_encode_xer(asn_TYPE_descriptor_t *td, const void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ConditionTypes_1_inherit_TYPE_descriptor(td);
	return td->op->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const ber_tlv_tag_t asn_DEF_ConditionTypes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (3 << 2))
};

static const asn_TYPE_operation_t asn_CHOICE_ConditionTypes = {
	ConditionTypes_free,
	ConditionTypes_print,
	0,
	ConditionTypes_decode_ber,
	ConditionTypes_encode_der,
	ConditionTypes_decode_xer,
	ConditionTypes_encode_xer,
	0,
	0,
	0,
	0,
	0,
	0
};

asn_TYPE_descriptor_t asn_DEF_ConditionTypes = {
	"ConditionTypes",
	"ConditionTypes",
	&asn_CHOICE_ConditionTypes,
	asn_DEF_ConditionTypes_tags_1,
	sizeof(asn_DEF_ConditionTypes_tags_1)
		/sizeof(asn_DEF_ConditionTypes_tags_1[0]), /* 1 */
	asn_DEF_ConditionTypes_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConditionTypes_tags_1)
		/sizeof(asn_DEF_ConditionTypes_tags_1[0]), /* 1 */
	{ 0, 0, ConditionTypes_constraint },
	0, 
	0,
	0	/* No specifics */
};

